[package]
name = "asset_loading"
authors.workspace = true
version.workspace = true
repository.workspace = true
edition = "2024"

[dependencies]
models = { path = "../models" }
bevy.workspace = true
bevy_seedling.workspace = true
ron.workspace = true


[lints]
workspace = true
